$(document).ready(function(){
    $("#feat1").click(function(){
        $("#featMore-01").toggle(300);
    });
    $("#feat2").click(function(){
        $("#featMore-02").toggle(300);
    });
    $("#feat3").click(function(){
        $("#featMore-03").toggle(300);
    });
    $("#overMoreBtn").click(function(){
        $("#overMore").toggle(300);
    });
    $("#abt1").click(function(){
        $("#abtMore-01").toggle(300);
    });
    $("#abt2").click(function(){
        $("#abtMore-02").toggle(300);
    });
    $("#abt3").click(function(){
        $("#abtMore-03").toggle(300);
    });
    $("#csth1").click(function(){
        $("#csthMore-01").toggle(300);
    });
    $("#csth2").click(function(){
        $("#csthMore-02").toggle(300);
    });
});